ai_settings:
  model: deepseek
  confidence_threshold: 0.6902142003036892
  max_trades_per_day: 5
  strategy_confidence: 0.7902142003036892
strategy:
  default: breakout
  risk_multiplier: 2.0
  lookback_period: 20
  breakout_threshold: 0.02
risk:
  max_position_size: 1500
  max_daily_loss: 750
  risk_level: high
updated: '2025-06-06T01:13:36.597380+00:00'
generated_by: strategy_recommender
confidence: 0.79
market_conditions: {}
